name: linux on license-checker

on:
  push:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: enviroment-setup
        run: |
          pip install pipenv
          pip env --python 3.10

      - name: install-target
        run: |
          pipenv install openai-whisper

      - name: Run Licenses Check
        run: |
          pipenv install pip-licenses
          pip-licenses
