name: linux on license-checker

on:
  push:

env:
  target: pipenv install openai-whisper

jobs:
  license-check:
    runs-on: ${{ martix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: enviroment-setup
        run: |
          pip install pipenv
          pipenv --python 3.10

      - name: install-target
        run: |
          $target

      - name: Run Licenses Check
        run: |
          pipenv install pip-licenses
          pipenv run pip-licenses -–with-urls –-with-description
  
